---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/7/15 9:48
---

--No More useless callings

RequestHandleMixin = CreateMixin(RequestHandleMixin)
RequestHandleMixin.type = "Request"

RequestHandleMixin.networkVars = {
    timeLastAutoAmmoPack = "private time",
    timeLastPrimaryRequestHandle = "private time",
}

function RequestHandleMixin:__initmixin()
    PROFILE("RequestHandleMixin:__initmixin")
    local now = Shared.GetTime()
    self.timeLastAutoAmmoPack = now
    self.timeLastPrimaryRequestHandle = now
end

if Server then
    
    local kAlertHandleDelay = 0.5
    function RequestHandleMixin:MedSelf()
        local time = Shared.GetTime()
        if time < self.timeLastPrimaryRequestHandle then return end

        if not MedPack.GetIsValidRecipient(self,self) then return end
        if self:GetResources() < kAutoMedPRes then return end

        self.timeLastPrimaryRequestHandle = time + kAutoMedCooldown
        self:AddResources(-kAutoMedPRes)

        self:AddHealth(MedPack.kHealth, false, true)
        self:AddRegeneration(MedPack.kRegen)
        self:TriggerEffects("medpack_pickup", { effecthostcoords = self:GetCoords() })
    end

    function RequestHandleMixin:AmmoSelf()
        local time = Shared.GetTime()
        if time < self.timeLastAutoAmmoPack then return end

        if not AmmoPack.GetIsValidRecipient(self,self) then return end
        if self:GetResources() < kAutoAmmoPRes then return end
        self:AddResources(-kAutoAmmoPRes)
        self.timeLastAutoAmmoPack = time + kAutoAmmoCooldown

        for i = 0, self:GetNumChildren() - 1 do
            local child = self:GetChildAtIndex(i)
            if child:isa("ClipWeapon") then
                if child:GiveAmmo(AmmoPack.kNumClips, false) then
                    consumedPack = true
                end
            end
        end

        self:TriggerEffects("ammopack_pickup", { effecthostcoords = self:GetCoords()})
    end
    
    function RequestHandleMixin:MistSelf()

        local time = Shared.GetTime()
        if time < self.timeLastPrimaryRequestHandle  then return end

        if self:GetResources() < kAutoMistPRes then return end
        self:AddResources(-kAutoMistPRes)
        self.timeLastPrimaryRequestHandle = time + kAutoMistCooldown
        
        CreateEntity(NutrientMist.kMapName,self:GetOrigin(),self:GetTeamNumber())
    end

    -- Returning TRUE here makes PlayingTeam:TriggerAlert swallow the request so
    -- the "player needs health/ammo" sound is NOT played to the commander;
    -- returning FALSE lets the alert (and its sound) reach the commander.
    --
    -- Human med/ammo requests must always reach the commander. When Military
    -- Protocol is not researched, also service the request locally through the
    -- auto-med/auto-ammo cooldown path.
    function RequestHandleMixin:HandleManualAlert(techId)

        if self.kIgnoreRequest then return false end

        local now = Shared.GetTime()
        local hasMilitaryProtocol = GetHasTech(self, kTechId.MilitaryProtocol)

        if techId == kTechId.MarineAlertNeedMedpack then
            if not hasMilitaryProtocol then
                self:AddTimedCallback(self.MedSelf, kAlertHandleDelay)
            end
            return false
        end

        if techId == kTechId.MarineAlertNeedAmmo then
            if not hasMilitaryProtocol then
                self:AddTimedCallback(self.AmmoSelf, kAlertHandleDelay)
            end
            return false
        end

        if techId == kTechId.AlienAlertNeedMist then
            self:AddTimedCallback(self.MistSelf,kAlertHandleDelay)
            --return true
        end

        return false
    end
end

