---
--- Generated by Luanalysis
--- Created by StriteR1996.
--- DateTime: 2023/7/15 9:48
---

--No More useless callings

RequestHandleMixin = CreateMixin(RequestHandleMixin)
RequestHandleMixin.type = "Request"

RequestHandleMixin.networkVars = {
    timeLastAutoAmmoPack = "private time",
    timeLastPrimaryRequestHandle = "private time",
}

function RequestHandleMixin:__initmixin()
    PROFILE("RequestHandleMixin:__initmixin")
    local now = Shared.GetTime()
    self.timeLastAutoAmmoPack = now
    self.timeLastPrimaryRequestHandle = now
end

if Server then
    
    local kAlertHandleDelay = 0.5
    function RequestHandleMixin:MedSelf()
        local time = Shared.GetTime()
        if time < self.timeLastPrimaryRequestHandle then return end

        if not MedPack.GetIsValidRecipient(self,self) then return end
        if self:GetResources() < kAutoMedPRes then return end

        self.timeLastPrimaryRequestHandle = time + kAutoMedCooldown
        self:AddResources(-kAutoMedPRes)

        self:AddHealth(MedPack.kHealth, false, true)
        self:AddRegeneration(MedPack.kRegen)
        self:TriggerEffects("medpack_pickup", { effecthostcoords = self:GetCoords() })
    end

    function RequestHandleMixin:AmmoSelf()
        local time = Shared.GetTime()
        if time < self.timeLastAutoAmmoPack then return end

        if not AmmoPack.GetIsValidRecipient(self,self) then return end
        if self:GetResources() < kAutoAmmoPRes then return end
        self:AddResources(-kAutoAmmoPRes)
        self.timeLastAutoAmmoPack = time + kAutoAmmoCooldown

        for i = 0, self:GetNumChildren() - 1 do
            local child = self:GetChildAtIndex(i)
            if child:isa("ClipWeapon") then
                if child:GiveAmmo(AmmoPack.kNumClips, false) then
                    consumedPack = true
                end
            end
        end

        self:TriggerEffects("ammopack_pickup", { effecthostcoords = self:GetCoords()})
    end
    
    function RequestHandleMixin:MistSelf()

        local time = Shared.GetTime()
        if time < self.timeLastPrimaryRequestHandle  then return end

        if self:GetResources() < kAutoMistPRes then return end
        self:AddResources(-kAutoMistPRes)
        self.timeLastPrimaryRequestHandle = time + kAutoMistCooldown
        
        CreateEntity(NutrientMist.kMapName,self:GetOrigin(),self:GetTeamNumber())
    end

    -- Decide how a marine med/ammo request should be serviced. Single source of
    -- truth shared by the CreateVoiceMessage override and HandleManualAlert.
    --
    --   "selfservice" - Military Protocol off AND not on cooldown: grant the
    --                   pack locally through the auto-med/auto-ammo path. Silent
    --                   (no voiceover, no commander alert).
    --   "commander"   - the requester is a human but cannot self-service right
    --                   now (on cooldown, or Military Protocol active): route the
    --                   request to the Marine commander with all the usual sounds.
    --   "suppress"    - the requester is a bot that cannot self-service: drop the
    --                   request so the commander is never bothered.
    --
    -- pass isMed = true for medpack requests, false for ammo requests.
    function RequestHandleMixin:GetPackRequestDecision(isMed)

        if self.kIgnoreRequest then return "suppress" end

        local team = self.GetTeam and self:GetTeam()
        local hasMilitaryProtocol = team and team.IsMilitaryProtocol and team:IsMilitaryProtocol()

        local now = Shared.GetTime()
        local onCooldown
        if isMed then
            onCooldown = now < self.timeLastPrimaryRequestHandle
        else
            onCooldown = now < self.timeLastAutoAmmoPack
        end

        if not hasMilitaryProtocol and not onCooldown then
            return "selfservice"
        end

        local isHuman = not (self.GetIsVirtual and self:GetIsVirtual())
        if isHuman then
            return "commander"
        end

        return "suppress"
    end

    -- Returning TRUE here makes PlayingTeam:TriggerAlert swallow the request so
    -- the "player needs health/ammo" sound is NOT played to the commander;
    -- returning FALSE lets the alert (and its sound) reach the commander.
    --
    -- The marine key-press path goes through CreateVoiceMessage (see
    -- CNBalance/NetworkMessages_Server.lua); this handler covers any other code
    -- that triggers a med/ammo alert directly and keeps the same routing rules.
    function RequestHandleMixin:HandleManualAlert(techId)

        if self.kIgnoreRequest then return false end

        if techId == kTechId.MarineAlertNeedMedpack or techId == kTechId.MarineAlertNeedAmmo then

            local isMed = (techId == kTechId.MarineAlertNeedMedpack)
            local decision = self:GetPackRequestDecision(isMed)

            if decision == "selfservice" then
                self:AddTimedCallback(isMed and self.MedSelf or self.AmmoSelf, kAlertHandleDelay)
                return true     -- handled locally; do not notify the commander
            elseif decision == "suppress" then
                return true     -- bot on cooldown / under Military Protocol; drop it
            end

            return false        -- "commander": let the alert + sounds reach the commander
        end

        if techId == kTechId.AlienAlertNeedMist then
            self:AddTimedCallback(self.MistSelf,kAlertHandleDelay)
            --return true
        end

        return false
    end
end

